version: '3'

services:
  app:
    build: .
    working_dir: /opt/app
    volumes:
      - ./:/opt/app
    env_file:
      - .env
    expose:
      - '5000'
    ports:
      - '5000:5000'
    depends_on:
      - db
  
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    expose:
      - '5432'
    restart: always
  
  pgadmin:
    container_name: pgadmin
    depends_on:
      - db
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    expose:
      - '80'
    ports:
      - '8080:80'
    restart: always
    